setlocal ENABLEDELAYEDEXPANSION
set maxn=0
set max=0

if %wn% lss 9 (set /a js=%js%+257) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %esb% neq -3 (set /a jq=%jq%+586) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %i% geq -9 (set /a gcf=%gcf%-603) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %d% neq 1 (set /a gcf=%gcf%+300) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %gy% gtr -1 (set /a g=%g%-973) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %rjx% lss 9 (set /a epp=%epp%+79) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %esb% equ 0 (set /a x=%x%-796) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %rf% lss 3 (set /a d=%d%-526) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %dma% gtr -8 (set /a qc=%qc%-610) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %aqr% gtr 5 (set /a gcf=%gcf%-831) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %jq% geq 583 (set /a wow=%wow%+705) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %esb% lss 10 (set /a gcf=%gcf%-135) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %aqr% neq 8 (set /a gcf=%gcf%-777) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %rjx% gtr -10 (set /a esb=%esb%+262) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %dma% gtr 3 (set /a x=%x%+259) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %rjx% neq -2 (set /a g=%g%+784) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %yzp% gtr -3 (set /a rjx=%rjx%-969) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %g% lss -182 (set /a wow=%wow%-401) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %rjx% leq -962 (set /a dma=%dma%+995) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %g% geq -194 (set /a vyy=%vyy%+290) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %gy% equ 0 (set /a vyy=%vyy%+4) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %wow% geq 314 (set /a vyy=%vyy%+295) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %j% geq -8 (set /a j=%j%-476) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %g% lss -195 (set /a u=%u%+84) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %gy% equ -4 (set /a g=%g%-422) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %cty% equ 0 (set /a yzp=%yzp%+523) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %g% gtr -195 (set /a cn=%cn%+938) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %g% leq -193 (set /a u=%u%+652) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %qc% lss -601 (set /a aqr=%aqr%-829) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %wow% lss 309 (set /a u=%u%-199) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %rf% geq 9 (set /a aqr=%aqr%+409) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %dma% gtr 990 (set /a dma=%dma%+556) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %i% neq 0 (set /a qc=%qc%+134) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %j% geq -476 (set /a qc=%qc%+238) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %js% lss 255 (set /a yzp=%yzp%-810) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %i% equ 0 (set /a i=%i%-898) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %tyg% leq -5 (set /a g=%g%+898) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %aqr% equ -832 (set /a j=%j%+130) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %l% gtr -7 (set /a tyg=%tyg%-504) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %l% geq -9 (set /a aqr=%aqr%-465) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %jq% neq 595 (set /a gcf=%gcf%-64) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %yzp% geq 515 (set /a wow=%wow%-102) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %i% equ -898 (set /a rf=%rf%-433) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %l% geq -6 (set /a rjx=%rjx%-334) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %cn% leq 947 (set /a rf=%rf%-395) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %qc% lss -376 (set /a u=%u%-724) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %gcf% geq -1281 (set /a epp=%epp%+309) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %cty% geq -5 (set /a zp=%zp%+367) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %aqr% leq -1287 (set /a aqr=%aqr%-265) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %wn% equ 0 (set /a u=%u%+359) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %aqr% neq -1550 (set /a vyy=%vyy%+587) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %u% leq 162 (set /a uxa=%uxa%-541) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %wow% geq 195 (set /a js=%js%+720) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %wn% gtr -3 (set /a d=%d%-857) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %gcf% equ -1279 (set /a cty=%cty%+958) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %x% geq -804 (set /a rf=%rf%-153) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %dma% leq 1560 (set /a cn=%cn%+921) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %qc% gtr -381 (set /a zp=%zp%-554) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %x% lss -799 (set /a jq=%jq%-83) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %cty% lss 968 (set /a qc=%qc%-912) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %tyg% equ -504 (set /a i=%i%-636) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %aqr% geq -1566 (set /a rjx=%rjx%-113) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %wow% gtr 198 (set /a js=%js%-184) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %cty% neq 958 (set /a qc=%qc%-519) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %u% gtr 166 (set /a aqr=%aqr%-281) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %vyy% leq 887 (set /a aqr=%aqr%+392) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %rjx% gtr -1420 (set /a cn=%cn%-179) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %cn% neq 1680 (set /a g=%g%-16) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %uxa% neq -541 (set /a d=%d%+260) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %yzp% lss 522 (set /a j=%j%-873) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %g% geq -191 (set /a rjx=%rjx%+737) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %qc% geq -1287 (set /a wow=%wow%+288) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %wn% gtr 5 (set /a j=%j%-844) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %uxa% gtr -546 (set /a i=%i%+91) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %d% equ -1383 (set /a yzp=%yzp%-12) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %zp% geq -189 (set /a cn=%cn%+247) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %dma% equ 1551 (set /a i=%i%+246) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %gy% geq -3 (set /a qc=%qc%-919) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %esb% lss 270 (set /a cn=%cn%+804) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %qc% neq -2197 (set /a uxa=%uxa%+593) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %esb% leq 264 (set /a yzp=%yzp%-562) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %zp% lss -181 (set /a rjx=%rjx%+850) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %j% neq -486 (set /a u=%u%-944) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %vyy% geq 881 (set /a vyy=%vyy%+970) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %u% lss -779 (set /a gy=%gy%+659) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %esb% equ 262 (set /a aqr=%aqr%-145) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %gcf% equ -1282 (set /a yzp=%yzp%+346) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %gcf% neq -1279 (set /a wow=%wow%+112) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %rjx% equ 171 (set /a vyy=%vyy%-120) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %qc% geq -2210 (set /a esb=%esb%+795) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %zp% equ -187 (set /a cty=%cty%-282) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %l% equ 0 (set /a uxa=%uxa%+683) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %jq% geq 589 (set /a epp=%epp%-185) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %cn% neq 2741 (set /a js=%js%+542) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %d% equ -1383 (set /a gy=%gy%+591) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %rf% neq -987 (set /a wow=%wow%-734) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %vyy% leq 1739 (set /a wow=%wow%-482) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %u% geq -785 (set /a uxa=%uxa%-231) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %d% neq -1385 (set /a gy=%gy%+153) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %js% gtr 1330 (set /a dma=%dma%+682) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %i% lss -1196 (set /a wn=%wn%+173) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %dma% gtr 2230 (set /a tyg=%tyg%+510) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %gcf% leq -1289 (set /a aqr=%aqr%+309) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %g% gtr -190 (set /a gcf=%gcf%+831) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %qc% equ -2203 (set /a g=%g%+457) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %gcf% neq -447 (set /a aqr=%aqr%+682) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %js% gtr 1328 (set /a cn=%cn%-75) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %cn% geq 2666 (set /a vyy=%vyy%-639) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %uxa% neq 499 (set /a j=%j%-119) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %gy% gtr 1399 (set /a i=%i%-312) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %aqr% neq -634 (set /a rjx=%rjx%-145) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %wow% equ -726 (set /a cty=%cty%+600) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %zp% lss -179 (set /a dma=%dma%+79) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %jq% leq 586 (set /a vyy=%vyy%+285) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %d% lss -1379 (set /a tyg=%tyg%+34) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %yzp% neq -44 (set /a u=%u%+320) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %wow% geq -730 (set /a esb=%esb%-229) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %cn% neq 2659 (set /a gy=%gy%-175) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %js% leq 1334 (set /a gy=%gy%+87) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %rjx% lss 35 (set /a wn=%wn%-725) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %gy% equ 1228 (set /a cty=%cty%+64) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %gcf% neq -438 (set /a tyg=%tyg%+809) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %uxa% gtr 500 (set /a zp=%zp%+526) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %wow% gtr -727 (set /a rjx=%rjx%-520) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %cty% gtr 1345 (set /a gy=%gy%+608) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %cn% equ 2656 (set /a u=%u%-847) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %zp% lss 343 (set /a dma=%dma%-728) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %wow% gtr -734 (set /a qc=%qc%+722) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %wn% neq -552 (set /a gy=%gy%-864) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %cn% equ 2656 (set /a l=%l%+53) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %gcf% gtr -446 (set /a rjx=%rjx%+674) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %jq% equ 586 (set /a i=%i%-647) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %cty% leq 1349 (set /a dma=%dma%-109) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %j% equ -595 (set /a d=%d%+263) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %rf% lss -972 (set /a rf=%rf%-835) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %js% geq 1332 (set /a esb=%esb%+504) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %wow% gtr -732 (set /a uxa=%uxa%+215) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %qc% neq -1472 (set /a l=%l%-240) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %aqr% gtr -639 (set /a tyg=%tyg%+754) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %d% gtr -1129 (set /a d=%d%+784) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %dma% equ 1482 (set /a u=%u%-528) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %aqr% neq -636 (set /a x=%x%-569) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %yzp% lss -49 (set /a uxa=%uxa%+163) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %x% neq -1365 (set /a qc=%qc%-88) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %yzp% leq -43 (set /a gy=%gy%-966) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %gy% equ 262 (set /a cn=%cn%+870) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %gy% gtr 263 (set /a x=%x%+511) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %epp% geq 380 (set /a qc=%qc%+245) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %vyy% geq 2018 (set /a rf=%rf%+718) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %u% neq -1302 (set /a aqr=%aqr%+494) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %wow% lss -734 (set /a esb=%esb%-211) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %epp% gtr 379 (set /a esb=%esb%+284) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %x% geq -1372 (set /a x=%x%+354) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %cty% neq 1349 (set /a g=%g%-378) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %js% lss 1338 (set /a wow=%wow%+405) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %yzp% neq -51 (set /a tyg=%tyg%-615) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %dma% equ 1475 (set /a rf=%rf%+475) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %aqr% leq -132 (set /a gy=%gy%-15) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %zp% neq 335 (set /a zp=%zp%+915) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %wn% geq -553 (set /a d=%d%-323) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %cn% neq 3517 (set /a g=%g%+525) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %gy% leq 248 (set /a l=%l%+13) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %i% neq -2147 (set /a gy=%gy%+687) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %gy% equ 934 (set /a tyg=%tyg%-487) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %vyy% equ 2014 (set /a rjx=%rjx%-444) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %yzp% lss -46 (set /a wn=%wn%+449) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %rf% neq -1337 (set /a cn=%cn%+651) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %jq% geq 578 (set /a zp=%zp%-888) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %esb% gtr 1616 (set /a uxa=%uxa%-966) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %tyg% neq 1109 (set /a wn=%wn%+219) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %cn% gtr 4176 (set /a dma=%dma%+599) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %epp% geq 387 (set /a x=%x%-486) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %yzp% neq -43 (set /a l=%l%-404) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %aqr% gtr -142 (set /a rjx=%rjx%+996) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %dma% equ 2079 (set /a g=%g%-215) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %i% gtr -2159 (set /a aqr=%aqr%+746) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %cn% geq 4174 (set /a gcf=%gcf%+301) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %vyy% equ 2016 (set /a qc=%qc%-700) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %d% geq -661 (set /a rjx=%rjx%-289) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %gcf% lss -138 (set /a vyy=%vyy%+278) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %wn% neq 118 (set /a g=%g%+659) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %l% leq -579 (set /a zp=%zp%+622) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %zp% geq 373 (set /a zp=%zp%+644) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %gy% geq 931 (set /a aqr=%aqr%+468) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %zp% gtr 359 (set /a wn=%wn%+608) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %gy% leq 942 (set /a js=%js%-985) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %epp% gtr 383 (set /a uxa=%uxa%-509) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %cty% leq 1340 (set /a tyg=%tyg%+134) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %dma% lss 2073 (set /a jq=%jq%-677) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %j% geq -600 (set /a yzp=%yzp%+146) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %dma% equ 2072 (set /a l=%l%-500) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %cty% leq 1341 (set /a cn=%cn%+399) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %wow% neq -321 (set /a rf=%rf%+521) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %wn% gtr 718 (set /a gcf=%gcf%+70) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %tyg% equ 1250 (set /a gcf=%gcf%-946) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %qc% equ -1936 (set /a cty=%cty%-398) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %qc% gtr -1936 (set /a qc=%qc%+105) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %g% neq 1082 (set /a g=%g%+16) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %vyy% gtr 2288 (set /a cty=%cty%-932) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %esb% neq 1616 (set /a gcf=%gcf%+293) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %esb% geq 1610 (set /a cn=%cn%-244) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %cn% neq 4338 (set /a rf=%rf%-790) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %wn% equ 724 (set /a dma=%dma%+87) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %j% gtr -598 (set /a cn=%cn%+191) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %d% leq -658 (set /a aqr=%aqr%-246) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %vyy% leq 2297 (set /a cn=%cn%+786) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %qc% lss -1932 (set /a g=%g%-211) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %l% geq -587 (set /a x=%x%-473) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %jq% leq 589 (set /a rjx=%rjx%-686) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %gcf% leq -1019 (set /a dma=%dma%-411) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %qc% leq -1933 (set /a u=%u%-596) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %rjx% gtr -476 (set /a l=%l%-60) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %zp% equ 366 (set /a wow=%wow%-910) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %u% neq -1916 (set /a gy=%gy%-854) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %wn% leq 729 (set /a jq=%jq%-698) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %d% neq -665 (set /a zp=%zp%+456) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %x% geq -1964 (set /a x=%x%+853) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %rjx% lss -478 (set /a aqr=%aqr%-282) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %cty% equ 10 (set /a tyg=%tyg%+975) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %wow% geq -1239 (set /a js=%js%-684) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %g% equ 879 (set /a uxa=%uxa%-702) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %tyg% leq 2231 (set /a g=%g%-602) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %dma% gtr 1742 (set /a cty=%cty%+987) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %cn% equ 5317 (set /a gy=%gy%+57) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %qc% gtr -1941 (set /a zp=%zp%+527) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %g% neq 282 (set /a tyg=%tyg%-689) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %rjx% gtr -478 (set /a gcf=%gcf%-11) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %uxa% lss -325 (set /a epp=%epp%-44) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %i% lss -2156 (set /a aqr=%aqr%-936) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %aqr% geq 841 (set /a i=%i%+119) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %uxa% gtr -330 (set /a yzp=%yzp%-46) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %esb% equ 1619 (set /a u=%u%+549) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %j% geq -598 (set /a zp=%zp%-412) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %gy% lss 89 (set /a cn=%cn%+865) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %g% gtr 283 (set /a yzp=%yzp%-366) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %j% leq -595 (set /a j=%j%-372) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %tyg% gtr 1532 (set /a zp=%zp%+879) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %x% gtr -1974 (set /a wow=%wow%-30) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %j% lss -966 (set /a dma=%dma%-288) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %epp% equ 344 (set /a zp=%zp%-419) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %x% lss -1964 (set /a tyg=%tyg%+304) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %j% lss -960 (set /a zp=%zp%-77) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %wn% lss 728 (set /a cty=%cty%-586) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %wow% equ -1261 (set /a wow=%wow%+271) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %dma% neq 1470 (set /a u=%u%-751) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %wn% neq 727 (set /a wow=%wow%+64) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %gy% leq 75 (set /a esb=%esb%+294) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %wow% gtr -918 (set /a jq=%jq%-559) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %gy% neq 73 (set /a cty=%cty%-283) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %g% neq 274 (set /a cty=%cty%-792) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %rjx% geq -482 (set /a l=%l%+589) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %jq% lss -116 (set /a gy=%gy%-659) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %aqr% leq 839 (set /a cn=%cn%+817) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %rjx% lss -467 (set /a l=%l%+682) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %rf% leq -2125 (set /a l=%l%+285) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %x% lss -1961 (set /a qc=%qc%-370) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %yzp% geq 47 (set /a l=%l%-582) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %js% equ -334 (set /a dma=%dma%-365) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %d% equ -659 (set /a js=%js%+397) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %aqr% leq 840 (set /a g=%g%+902) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %rf% geq -2139 (set /a x=%x%+129) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %gcf% lss -1041 (set /a g=%g%+704) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %uxa% gtr -332 (set /a cn=%cn%+207) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %js% lss 70 (set /a epp=%epp%-517) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %qc% leq -2305 (set /a cn=%cn%-125) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %tyg% gtr 1844 (set /a x=%x%-187) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %cty% lss -661 (set /a gy=%gy%+1) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %qc% neq -2306 (set /a js=%js%-224) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %gcf% leq -1025 (set /a x=%x%-627) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %g% lss 1186 (set /a yzp=%yzp%-426) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %wow% geq -933 (set /a uxa=%uxa%+839) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %gy% leq 87 (set /a u=%u%+688) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %aqr% lss 834 (set /a jq=%jq%+453) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %d% geq -660 (set /a tyg=%tyg%-370) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %gy% neq 89 (set /a l=%l%-81) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %uxa% equ 510 (set /a zp=%zp%+184) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %gcf% equ -1034 (set /a gcf=%gcf%+97) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %x% neq -2468 (set /a tyg=%tyg%-508) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %j% lss -960 (set /a cty=%cty%+89) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %rf% geq -2132 (set /a jq=%jq%-416) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %cty% geq -577 (set /a rf=%rf%-846) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %vyy% leq 2294 (set /a uxa=%uxa%+315) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %vyy% equ 2294 (set /a g=%g%-191) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %wow% equ -934 (set /a js=%js%+557) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %qc% geq -2313 (set /a u=%u%-382) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %wow% gtr -929 (set /a dma=%dma%+841) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %dma% lss 1932 (set /a u=%u%-6) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %js% equ 63 (set /a aqr=%aqr%+75) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %gcf% lss -928 (set /a jq=%jq%+640) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %j% neq -967 (set /a wn=%wn%-992) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %wn% neq 726 (set /a uxa=%uxa%+577) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %rjx% lss -467 (set /a g=%g%-458) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %x% equ -2468 (set /a epp=%epp%-141) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %cty% lss -576 (set /a l=%l%+617) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %yzp% neq -377 (set /a gy=%gy%-542) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %uxa% lss 1410 (set /a cty=%cty%+99) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %g% gtr 521 (set /a tyg=%tyg%-358) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %uxa% leq 1401 (set /a wn=%wn%-514) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %j% gtr -960 (set /a dma=%dma%+110) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %jq% leq 569 (set /a js=%js%-359) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %epp% lss -312 (set /a epp=%epp%-266) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %jq% gtr 557 (set /a x=%x%-473) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %wn% equ 730 (set /a vyy=%vyy%+890) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %gcf% neq -932 (set /a zp=%zp%-379) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %jq% equ 565 (set /a u=%u%-46) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %l% neq 256 (set /a tyg=%tyg%-410) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %js% neq -303 (set /a i=%i%-320) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %i% geq -2482 (set /a l=%l%-670) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %u% lss -2391 (set /a i=%i%+788) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %cty% equ -476 (set /a l=%l%+23) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %rf% leq -2969 (set /a tyg=%tyg%-364) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %epp% geq -584 (set /a gy=%gy%-394) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %aqr% neq 907 (set /a esb=%esb%-645) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %x% lss -2935 (set /a epp=%epp%-842) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %l% equ -392 (set /a js=%js%+289) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %gcf% equ -937 (set /a tyg=%tyg%-405) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %epp% equ -1419 (set /a vyy=%vyy%+58) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %u% equ -2398 (set /a gy=%gy%-110) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %epp% gtr -1426 (set /a vyy=%vyy%+789) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %zp% geq 1117 (set /a qc=%qc%-463) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %esb% equ 1616 (set /a gcf=%gcf%+859) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %js% lss 2 (set /a u=%u%-99) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %tyg% equ -67 (set /a epp=%epp%+111) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %d% lss -661 (set /a jq=%jq%-536) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %dma% leq 1936 (set /a js=%js%+506) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %j% geq -971 (set /a rjx=%rjx%+58) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %tyg% leq -64 (set /a wn=%wn%+513) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %aqr% geq 902 (set /a wow=%wow%-816) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %x% equ -2941 (set /a gcf=%gcf%-957) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %yzp% leq -377 (set /a uxa=%uxa%+39) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %g% leq 531 (set /a wn=%wn%+824) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %l% geq -394 (set /a gcf=%gcf%-927) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %l% equ -392 (set /a x=%x%+655) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %tyg% gtr -59 (set /a g=%g%+767) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %epp% neq -1318 (set /a dma=%dma%-493) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %epp% geq -1318 (set /a esb=%esb%-587) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %cty% geq -479 (set /a wow=%wow%+996) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %epp% neq -1311 (set /a l=%l%-119) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %uxa% lss 1444 (set /a gy=%gy%+935) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %zp% geq 1121 (set /a gcf=%gcf%+428) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %x% gtr -2293 (set /a js=%js%-999) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %epp% neq -1305 (set /a uxa=%uxa%-438) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %yzp% leq -380 (set /a gcf=%gcf%+623) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %gcf% lss -1530 (set /a j=%j%-256) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %d% geq -662 (set /a l=%l%-183) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %x% lss -2279 (set /a wn=%wn%-945) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %epp% equ -1311 (set /a i=%i%+953) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %js% gtr -1016 (set /a vyy=%vyy%-434) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %epp% lss -1308 (set /a yzp=%yzp%+695) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %l% equ -575 (set /a d=%d%+975) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %j% lss -1216 (set /a uxa=%uxa%+218) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %tyg% equ -67 (set /a gcf=%gcf%+413) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %zp% neq 1125 (set /a wow=%wow%-380) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %wn% gtr 1113 (set /a cn=%cn%-166) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %l% neq -581 (set /a rjx=%rjx%-878) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %g% leq 531 (set /a esb=%esb%-745) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %esb% lss 292 (set /a aqr=%aqr%-14) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %jq% equ 565 (set /a j=%j%+405) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %wn% equ 1124 (set /a vyy=%vyy%+657) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %qc% gtr -2763 (set /a j=%j%+624) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %esb% lss 289 (set /a rf=%rf%-711) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %gy% geq 512 (set /a uxa=%uxa%+453) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %js% geq -1009 (set /a i=%i%+593) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %j% gtr -826 (set /a qc=%qc%-413) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %epp% equ -1311 (set /a tyg=%tyg%-395) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %g% geq 524 (set /a cty=%cty%+911) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %esb% geq 277 (set /a yzp=%yzp%-259) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %vyy% gtr 2643 (set /a dma=%dma%+812) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %gcf% geq -1121 (set /a wow=%wow%+887) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %rf% lss -3686 (set /a uxa=%uxa%+906) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %js% gtr -1002 (set /a l=%l%-816) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %tyg% geq -462 (set /a aqr=%aqr%-123) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %uxa% lss 2590 (set /a x=%x%+413) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %wow% leq 142 (set /a tyg=%tyg%+141) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %gcf% gtr -1118 (set /a cn=%cn%-138) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %wn% lss 1117 (set /a i=%i%+665) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %gy% gtr 505 (set /a wow=%wow%-250) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %l% neq -569 (set /a wow=%wow%+751) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %x% geq -1879 (set /a j=%j%+334) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %uxa% geq 2575 (set /a i=%i%-963) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %wn% equ 1106 (set /a uxa=%uxa%+395) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %esb% neq 290 (set /a dma=%dma%-130) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %zp% gtr 1122 (set /a l=%l%+171) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %uxa% lss 2576 (set /a esb=%esb%+288) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %i% gtr -445 (set /a wn=%wn%-672) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %jq% equ 565 (set /a uxa=%uxa%-593) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %yzp% geq 52 (set /a cty=%cty%-247) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %cn% equ 6907 (set /a vyy=%vyy%+480) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %uxa% leq 1982 (set /a js=%js%+402) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %cn% lss 6913 (set /a l=%l%+121) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %i% leq -433 (set /a rjx=%rjx%-692) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %cty% geq 186 (set /a g=%g%+827) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %i% geq -449 (set /a d=%d%-333) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %u% gtr -2502 (set /a zp=%zp%+438) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %cn% geq 6902 (set /a gy=%gy%+418) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %uxa% neq 1980 (set /a x=%x%-665) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %l% equ -283 (set /a zp=%zp%-497) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %rf% geq -3694 (set /a i=%i%-51) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %gy% lss 931 (set /a dma=%dma%+792) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %wn% leq 435 (set /a dma=%dma%+189) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %g% neq 1347 (set /a cty=%cty%-337) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %dma% equ 2919 (set /a zp=%zp%-436) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %rjx% leq -1980 (set /a yzp=%yzp%+184) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %qc% leq -3174 (set /a gcf=%gcf%+688) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %zp% leq 636 (set /a u=%u%-536) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %rjx% neq -1989 (set /a d=%d%-31) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %wow% geq 651 (set /a esb=%esb%-523) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %zp% geq 632 (set /a gy=%gy%+566) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %zp% equ 630 (set /a vyy=%vyy%-190) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %i% lss -486 (set /a tyg=%tyg%+53) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %i% lss -482 (set /a x=%x%+543) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %epp% neq -1319 (set /a uxa=%uxa%-403) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %u% equ -3033 (set /a i=%i%+880) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %gcf% lss -428 (set /a wn=%wn%-172) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %cn% gtr 6904 (set /a qc=%qc%-316) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %rf% equ -3688 (set /a gcf=%gcf%-864) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %uxa% leq 1583 (set /a esb=%esb%-344) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %js% geq -1006 (set /a i=%i%-234) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %d% lss -45 (set /a x=%x%+306) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %rjx% geq -1983 (set /a vyy=%vyy%-256) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %epp% gtr -1309 (set /a u=%u%+498) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %u% equ -3033 (set /a esb=%esb%-915) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %esb% lss -624 (set /a i=%i%+910) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %qc% gtr -3505 (set /a l=%l%-781) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %u% lss -3032 (set /a g=%g%-803) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %u% equ -3033 (set /a dma=%dma%-392) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %vyy% neq 2929 (set /a cty=%cty%+216) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %gy% equ 930 (set /a zp=%zp%-12) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %tyg% geq -269 (set /a gy=%gy%+35) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %wow% neq 642 (set /a wow=%wow%+824) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %epp% geq -1319 (set /a js=%js%+974) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %dma% neq 2527 (set /a gcf=%gcf%+883) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %cty% neq 72 (set /a jq=%jq%+339) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %zp% neq 627 (set /a yzp=%yzp%-751) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %x% lss -1679 (set /a tyg=%tyg%+90) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %rjx% lss -1976 (set /a vyy=%vyy%-212) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %epp% leq -1302 (set /a wow=%wow%+642) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %x% leq -1689 (set /a d=%d%+643) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %vyy% neq 2728 (set /a i=%i%+25) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %tyg% equ -178 (set /a js=%js%-522) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %epp% equ -1311 (set /a js=%js%+880) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %x% equ -1689 (set /a l=%l%-899) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %g% lss 563 (set /a u=%u%-459) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %i% gtr 1083 (set /a tyg=%tyg%+485) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %dma% lss 2537 (set /a zp=%zp%+944) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %cty% gtr 57 (set /a cn=%cn%+867) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %jq% equ 904 (set /a i=%i%+95) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %d% equ 595 (set /a gcf=%gcf%-548) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %aqr% geq 766 (set /a gcf=%gcf%+35) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %yzp% neq -501 (set /a x=%x%-420) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %yzp% equ -500 (set /a x=%x%-308) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %l% leq -1961 (set /a vyy=%vyy%-407) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %j% lss -476 (set /a gy=%gy%-623) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %g% gtr 547 (set /a u=%u%-932) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %js% gtr 324 (set /a zp=%zp%-18) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %cn% gtr 7771 (set /a g=%g%-776) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %cn% equ 7764 (set /a jq=%jq%-581) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %g% lss -215 (set /a zp=%zp%+392) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %i% lss 1185 (set /a vyy=%vyy%-266) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %jq% lss 906 (set /a tyg=%tyg%+600) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %aqr% neq 770 (set /a wow=%wow%-480) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %j% leq -488 (set /a yzp=%yzp%+97) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %wow% equ 1284 (set /a cn=%cn%-212) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %rjx% equ -1992 (set /a vyy=%vyy%+247) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %uxa% neq 1584 (set /a x=%x%+13) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %vyy% lss 2330 (set /a wow=%wow%+929) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %vyy% neq 2313 (set /a qc=%qc%+515) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %u% leq -4424 (set /a wow=%wow%+484) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %wow% gtr 2699 (set /a wn=%wn%+251) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %d% gtr 585 (set /a dma=%dma%+128) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %cn% gtr 7564 (set /a epp=%epp%-429) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %gy% lss 344 (set /a tyg=%tyg%+401) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %qc% equ -2975 (set /a dma=%dma%-757) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %tyg% equ 1308 (set /a rjx=%rjx%+124) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %wn% lss 279 (set /a j=%j%+258) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %u% neq -4431 (set /a zp=%zp%+265) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %epp% leq -1308 (set /a epp=%epp%+850) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %cty% gtr 64 (set /a jq=%jq%+875) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %yzp% leq -509 (set /a esb=%esb%+585) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %vyy% neq 2313 (set /a qc=%qc%-663) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %rf% lss -3682 (set /a cn=%cn%-194) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %rjx% gtr -1862 (set /a i=%i%-821) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %i% neq 354 (set /a qc=%qc%+768) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %gcf% neq -1805 (set /a rf=%rf%+949) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %gcf% equ -1807 (set /a wow=%wow%-350) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %dma% leq 2663 (set /a l=%l%+72) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %x% leq -2106 (set /a qc=%qc%-201) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %esb% equ -631 (set /a cty=%cty%+576) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %i% geq 358 (set /a uxa=%uxa%-387) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %uxa% geq 1193 (set /a uxa=%uxa%+189) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %qc% gtr -3089 (set /a i=%i%-193) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %wow% equ 2697 (set /a gcf=%gcf%-164) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %cn% lss 7364 (set /a aqr=%aqr%-154) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %j% lss -228 (set /a dma=%dma%+145) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %rf% gtr -2749 (set /a cn=%cn%-314) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %yzp% gtr -509 (set /a qc=%qc%-976) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %j% equ -226 (set /a tyg=%tyg%+277) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %yzp% lss -501 (set /a l=%l%+339) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %js% gtr 320 (set /a qc=%qc%+615) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %rf% geq -2743 (set /a x=%x%-678) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %g% gtr -228 (set /a rjx=%rjx%-777) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %vyy% leq 2320 (set /a rf=%rf%-151) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %u% leq -4422 (set /a js=%js%-591) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %d% neq 585 (set /a i=%i%+166) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %esb% lss -634 (set /a cn=%cn%-615) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %dma% gtr 2649 (set /a qc=%qc%+148) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %d% equ 595 (set /a gy=%gy%+93) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %js% lss -256 (set /a esb=%esb%-265) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %x% neq -2795 (set /a wn=%wn%+784) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %yzp% lss -499 (set /a rf=%rf%+123) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %rf% leq -2777 (set /a tyg=%tyg%+51) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %tyg% neq 1575 (set /a dma=%dma%+273) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %uxa% equ 1386 (set /a g=%g%-546) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %l% lss -1546 (set /a j=%j%+787) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %qc% leq -3289 (set /a rf=%rf%+97) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %uxa% leq 1388 (set /a x=%x%+621) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %esb% leq -894 (set /a cn=%cn%-760) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %zp% leq 2197 (set /a jq=%jq%-89) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %wow% equ 2697 (set /a uxa=%uxa%+485) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %rjx% equ -2638 (set /a j=%j%+971) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %l% neq -1552 (set /a rjx=%rjx%+117) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %wn% lss 1059 (set /a yzp=%yzp%-335) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %j% leq 1541 (set /a gy=%gy%+871) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %yzp% neq -852 (set /a tyg=%tyg%+602) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %cn% gtr 6293 (set /a rjx=%rjx%+852) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %cn% gtr 6293 (set /a g=%g%-893) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %cn% gtr 6297 (set /a uxa=%uxa%-524) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %i% lss 347 (set /a yzp=%yzp%+389) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %rf% gtr -2667 (set /a epp=%epp%+502) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %yzp% gtr -453 (set /a dma=%dma%-323) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %wow% leq 2706 (set /a l=%l%-921) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %jq% gtr 1777 (set /a yzp=%yzp%+534) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %rjx% neq -1784 (set /a yzp=%yzp%-94) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %vyy% neq 2320 (set /a uxa=%uxa%+254) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %gy% leq 1313 (set /a i=%i%-224) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %vyy% lss 2318 (set /a u=%u%-466) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %cn% leq 6299 (set /a epp=%epp%+751) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %tyg% geq 2197 (set /a qc=%qc%+316) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %epp% equ 290 (set /a d=%d%-666) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %js% neq -274 (set /a g=%g%+398) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %cn% equ 6304 (set /a rf=%rf%-482) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %cty% equ 643 (set /a vyy=%vyy%+295) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %i% neq 108 (set /a wn=%wn%+540) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %wow% neq 2691 (set /a qc=%qc%-334) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %dma% lss 2935 (set /a d=%d%-315) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %d% neq -385 (set /a qc=%qc%+860) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %gy% gtr 1296 (set /a qc=%qc%+202) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %vyy% gtr 2610 (set /a wow=%wow%+67) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %vyy% neq 2621 (set /a esb=%esb%-880) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %d% leq -383 (set /a cn=%cn%-985) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %g% equ -1263 (set /a epp=%epp%-435) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %u% neq -4419 (set /a gcf=%gcf%-559) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %yzp% geq -23 (set /a aqr=%aqr%-979) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %wn% lss 1597 (set /a jq=%jq%+905) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %x% geq -2165 (set /a cn=%cn%-679) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %j% neq 1532 (set /a rf=%rf%-590) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %wn% leq 1598 (set /a l=%l%+73) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %d% gtr -388 (set /a qc=%qc%-804) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %zp% lss 2198 (set /a j=%j%+42) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %qc% lss -3366 (set /a tyg=%tyg%+636) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %vyy% neq 2613 (set /a gy=%gy%+209) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %x% lss -2158 (set /a l=%l%-725) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %j% geq 1531 (set /a qc=%qc%-54) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %js% lss -258 (set /a cty=%cty%+896) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %d% leq -377 (set /a u=%u%+718) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %esb% geq -1785 (set /a l=%l%-654) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %i% leq 120 (set /a dma=%dma%-912) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %cty% leq 1543 (set /a uxa=%uxa%+827) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %g% geq -1271 (set /a rf=%rf%+871) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %tyg% gtr 2814 (set /a uxa=%uxa%-77) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %i% leq 121 (set /a d=%d%-59) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %cn% equ 5309 (set /a dma=%dma%-792) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %yzp% geq -15 (set /a zp=%zp%+930) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %d% equ -435 (set /a gy=%gy%-956) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %j% leq 1540 (set /a wn=%wn%+205) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %cty% geq 1536 (set /a d=%d%+830) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %u% neq -3700 (set /a tyg=%tyg%-552) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %gcf% neq -2533 (set /a rf=%rf%-616) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %rf% geq -1793 (set /a yzp=%yzp%+87) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %dma% leq 1226 (set /a uxa=%uxa%-886) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %uxa% lss 1741 (set /a g=%g%+278) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %vyy% gtr 2614 (set /a j=%j%-1) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %rjx% equ -1786 (set /a d=%d%-899) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %vyy% geq 2606 (set /a rjx=%rjx%-238) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %d% leq -505 (set /a cn=%cn%-663) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %l% neq -3785 (set /a rjx=%rjx%-805) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %aqr% neq -206 (set /a tyg=%tyg%-610) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %yzp% leq -12 (set /a gcf=%gcf%+842) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %l% leq -3772 (set /a tyg=%tyg%-361) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %dma% neq 1219 (set /a wow=%wow%+717) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %gcf% neq -1695 (set /a vyy=%vyy%-182) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %vyy% geq 2428 (set /a l=%l%-972) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %gy% leq 1517 (set /a cn=%cn%+106) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %cn% geq 4749 (set /a g=%g%-598) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %rf% leq -1808 (set /a l=%l%-653) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %esb% neq -1781 (set /a epp=%epp%+768) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %uxa% neq 1740 (set /a rf=%rf%+566) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %cn% equ 4752 (set /a aqr=%aqr%+639) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %u% equ -3699 (set /a wn=%wn%-877) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %vyy% geq 2427 (set /a uxa=%uxa%+7) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %qc% neq -3430 (set /a yzp=%yzp%+107) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %esb% leq -1776 (set /a yzp=%yzp%-426) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %x% lss -2164 (set /a epp=%epp%+102) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %jq% equ 2684 (set /a u=%u%-396) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %jq% leq 2686 (set /a dma=%dma%+6) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %gcf% gtr -1698 (set /a cn=%cn%-739) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %cty% equ 1539 (set /a gcf=%gcf%+470) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %vyy% neq 2433 (set /a gy=%gy%+781) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %dma% lss 1236 (set /a vyy=%vyy%-238) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %wn% neq 1801 (set /a wow=%wow%+670) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %jq% lss 2686 (set /a i=%i%+230) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %wow% equ 3481 (set /a wn=%wn%+500) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %j% lss 1536 (set /a wow=%wow%-865) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %jq% equ 2684 (set /a x=%x%-733) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %gy% geq 1513 (set /a cty=%cty%-531) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %esb% lss -1768 (set /a g=%g%+399) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %rf% equ -1233 (set /a x=%x%+201) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %d% lss -515 (set /a cn=%cn%+394) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %wow% geq 2615 (set /a epp=%epp%-953) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %u% neq -4095 (set /a qc=%qc%-639) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %vyy% gtr 2191 (set /a i=%i%+935) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %gcf% neq -1218 (set /a g=%g%+846) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %yzp% gtr -334 (set /a epp=%epp%-89) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %epp% geq -317 (set /a qc=%qc%+143) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %zp% neq 3132 (set /a gy=%gy%-256) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %rjx% gtr -2831 (set /a tyg=%tyg%+545) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %gcf% neq -1226 (set /a cn=%cn%-913) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %d% equ -514 (set /a esb=%esb%-410) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %tyg% leq 1849 (set /a rjx=%rjx%+71) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %yzp% gtr -336 (set /a rjx=%rjx%-127) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %gcf% geq -1221 (set /a jq=%jq%-206) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %gcf% gtr -1225 (set /a i=%i%+800) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %gy% lss 1263 (set /a aqr=%aqr%+98) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %gcf% leq -1213 (set /a gcf=%gcf%-163) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %zp% equ 3131 (set /a cty=%cty%+965) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %cty% lss 1976 (set /a rjx=%rjx%+969) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %x% equ -2698 (set /a uxa=%uxa%+51) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %wow% equ 2616 (set /a u=%u%+380) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %rjx% geq -1922 (set /a tyg=%tyg%+715) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %yzp% geq -323 (set /a zp=%zp%-825) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %x% gtr -2702 (set /a zp=%zp%-292) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %d% leq -505 (set /a esb=%esb%-415) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %esb% gtr -2609 (set /a wn=%wn%-240) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %rf% equ -1233 (set /a gy=%gy%+882) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %gcf% leq -1384 (set /a vyy=%vyy%+638) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %jq% leq 2479 (set /a tyg=%tyg%+63) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %uxa% lss 1797 (set /a dma=%dma%-38) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %wow% lss 2619 (set /a qc=%qc%+289) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %yzp% geq -330 (set /a d=%d%+342) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %js% lss -271 (set /a cty=%cty%+650) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %esb% equ -2601 (set /a l=%l%-129) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %j% gtr 1531 (set /a jq=%jq%+453) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %i% gtr 2084 (set /a esb=%esb%-11) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %wow% lss 2620 (set /a wow=%wow%-729) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %uxa% leq 1796 (set /a x=%x%+132) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %vyy% leq 2832 (set /a l=%l%-818) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %yzp% neq -334 (set /a tyg=%tyg%-804) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %rf% neq -1233 (set /a wow=%wow%+285) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %wn% neq 2061 (set /a zp=%zp%+329) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %js% equ -265 (set /a u=%u%+720) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %aqr% neq 528 (set /a gcf=%gcf%+85) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %jq% neq 2472 (set /a wow=%wow%+303) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %cty% lss 1965 (set /a vyy=%vyy%-366) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %cty% equ 1973 (set /a yzp=%yzp%+598) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %jq% geq 2471 (set /a rf=%rf%+685) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %jq% leq 2487 (set /a vyy=%vyy%-385) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %esb% geq -2598 (set /a aqr=%aqr%+103) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %uxa% equ 1793 (set /a d=%d%+427) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %zp% lss 2849 (set /a rjx=%rjx%-736) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %esb% leq -2600 (set /a x=%x%+991) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %gcf% leq -1391 (set /a gy=%gy%+642) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %wow% lss 2195 (set /a yzp=%yzp%+726) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %u% equ -3002 (set /a zp=%zp%+582) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %cn% gtr 3093 (set /a rf=%rf%+354) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %g% neq -342 (set /a g=%g%-150) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %wn% geq 2060 (set /a uxa=%uxa%-381) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %qc% lss -3628 (set /a wow=%wow%-145) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %qc% leq -3626 (set /a g=%g%+589) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %js% equ -265 (set /a jq=%jq%+643) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %cty% equ 1973 (set /a yzp=%yzp%+768) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %aqr% leq 533 (set /a vyy=%vyy%-448) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %cn% leq 3103 (set /a uxa=%uxa%-507) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %aqr% geq 521 (set /a gy=%gy%-134) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %rf% neq -194 (set /a x=%x%-868) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %cn% geq 3093 (set /a gcf=%gcf%+355) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %tyg% equ 1822 (set /a rf=%rf%-639) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %wow% geq 2048 (set /a gcf=%gcf%-671) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %gy% neq 2012 (set /a jq=%jq%+615) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %cn% lss 3096 (set /a zp=%zp%+910) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %wow% lss 2055 (set /a rjx=%rjx%+949) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %jq% neq 3731 (set /a esb=%esb%-623) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %qc% neq -3634 (set /a g=%g%+799) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %rf% geq -196 (set /a uxa=%uxa%-352) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %jq% neq 3729 (set /a gcf=%gcf%-229) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %rf% gtr -200 (set /a zp=%zp%+785) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %gcf% lss -1251 (set /a i=%i%-150) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %dma% neq 1189 (set /a gcf=%gcf%-463) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %wn% equ 2061 (set /a j=%j%-424) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %gcf% leq -1715 (set /a l=%l%+412) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %u% leq -2994 (set /a aqr=%aqr%-646) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %l% leq -4471 (set /a i=%i%+195) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %cty% lss 1982 (set /a rjx=%rjx%+291) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %dma% neq 1198 (set /a epp=%epp%-459) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %vyy% gtr 1998 (set /a u=%u%-909) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %vyy% gtr 1994 (set /a uxa=%uxa%+208) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %i% equ 1928 (set /a u=%u%-727) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %l% equ -4468 (set /a x=%x%-402) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %cn% gtr 3095 (set /a u=%u%-459) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %jq% lss 3733 (set /a j=%j%+253) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %rf% gtr -204 (set /a vyy=%vyy%+143) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %tyg% lss 1822 (set /a rjx=%rjx%+560) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %jq% gtr 3732 (set /a cn=%cn%+602) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %wn% geq 2066 (set /a wow=%wow%+231) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %x% gtr -1972 (set /a js=%js%-40) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %rjx% geq -842 (set /a gcf=%gcf%-591) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %u% leq -5090 (set /a wn=%wn%-612) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %j% geq 1100 (set /a vyy=%vyy%+60) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %tyg% equ 1819 (set /a cty=%cty%+207) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %dma% lss 1197 (set /a wow=%wow%+862) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %i% leq 1936 (set /a cn=%cn%-534) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %wow% equ 2907 (set /a d=%d%-380) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %dma% lss 1199 (set /a x=%x%+48) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %dma% neq 1191 (set /a yzp=%yzp%+955) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %l% leq -4467 (set /a dma=%dma%-372) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %wow% neq 2909 (set /a uxa=%uxa%-83) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %u% gtr -5102 (set /a u=%u%-383) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %cn% leq 3169 (set /a cn=%cn%-691) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %jq% equ 3733 (set /a vyy=%vyy%+952) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %wn% lss 1444 (set /a j=%j%+231) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %x% geq -1931 (set /a i=%i%+988) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %x% gtr -1936 (set /a cn=%cn%+459) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %epp% neq -779 (set /a js=%js%-714) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %cn% leq 2936 (set /a gy=%gy%-751) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %vyy% neq 2203 (set /a epp=%epp%-45) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %i% neq 2916 (set /a aqr=%aqr%+251) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %x% equ -1929 (set /a zp=%zp%+248) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %tyg% gtr 1814 (set /a vyy=%vyy%+917) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %rjx% gtr -855 (set /a l=%l%+906) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %aqr% geq -120 (set /a wn=%wn%+262) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %j% geq 1108 (set /a js=%js%-293) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %uxa% lss 671 (set /a g=%g%-507) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %uxa% lss 680 (set /a tyg=%tyg%-848) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %cn% neq 2931 (set /a tyg=%tyg%+449) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %d% geq -474 (set /a jq=%jq%+43) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %rjx% neq -852 (set /a uxa=%uxa%-510) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %cn% leq 2936 (set /a u=%u%+15) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %uxa% lss 688 (set /a rf=%rf%-467) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %j% lss 1114 (set /a dma=%dma%-40) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %l% gtr -3564 (set /a cn=%cn%+256) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %cty% leq 2173 (set /a uxa=%uxa%+193) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %epp% leq -773 (set /a cn=%cn%+472) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %qc% neq -3621 (set /a g=%g%-509) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %wow% geq 2902 (set /a x=%x%+909) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %rf% gtr -663 (set /a j=%j%+809) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %x% gtr -1028 (set /a epp=%epp%+458) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %wn% gtr 1707 (set /a cty=%cty%+210) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %rjx% leq -848 (set /a wn=%wn%-778) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %l% equ -3570 (set /a zp=%zp%+745) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %rjx% neq -852 (set /a dma=%dma%-86) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %aqr% gtr -126 (set /a dma=%dma%-964) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %wow% equ 2909 (set /a x=%x%-741) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %esb% leq -3217 (set /a cn=%cn%-751) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %qc% geq -3636 (set /a cty=%cty%-910) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %epp% geq -321 (set /a gcf=%gcf%+496) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %epp% geq -322 (set /a rf=%rf%+516) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %dma% leq -187 (set /a dma=%dma%-112) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %zp% geq 4451 (set /a yzp=%yzp%+376) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %qc% geq -3629 (set /a js=%js%+829) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %dma% gtr -188 (set /a rf=%rf%-310) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %wow% geq 2899 (set /a gy=%gy%-312) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %dma% gtr -186 (set /a cn=%cn%-889) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %uxa% gtr 682 (set /a g=%g%+667) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %u% neq -5462 (set /a u=%u%+201) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %yzp% gtr 3082 (set /a cty=%cty%-589) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %wow% neq 2907 (set /a gy=%gy%-274) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %tyg% equ 1420 (set /a u=%u%+533) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %d% geq -469 (set /a zp=%zp%+937) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %cn% equ 2024 (set /a jq=%jq%-18) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %rjx% leq -850 (set /a cn=%cn%+59) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %x% gtr -1026 (set /a dma=%dma%+172) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %gcf% gtr -1231 (set /a jq=%jq%-129) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %jq% lss 3627 (set /a wn=%wn%-957) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %wn% leq 939 (set /a uxa=%uxa%+989) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %x% neq -1013 (set /a jq=%jq%-390) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %g% lss 385 (set /a js=%js%+251) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %tyg% leq 1424 (set /a jq=%jq%-572) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %vyy% gtr 3122 (set /a g=%g%-265) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %x% gtr -1025 (set /a rjx=%rjx%+789) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %d% lss -465 (set /a gcf=%gcf%+838) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %gcf% neq -387 (set /a g=%g%+564) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %yzp% neq 3087 (set /a vyy=%vyy%+188) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %x% lss -1015 (set /a i=%i%-912) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %x% leq -1019 (set /a cty=%cty%-768) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %wow% equ 2906 (set /a wn=%wn%-175) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %qc% gtr -3627 (set /a wow=%wow%+534) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %x% geq -1026 (set /a js=%js%+247) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %gy% equ 944 (set /a vyy=%vyy%-894) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %rf% neq -445 (set /a x=%x%-150) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %wn% lss 932 (set /a dma=%dma%-766) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %zp% geq 5383 (set /a gcf=%gcf%+53) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %u% geq -4740 (set /a g=%g%-9) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %vyy% lss 2423 (set /a yzp=%yzp%+425) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %vyy% gtr 2406 (set /a aqr=%aqr%+407) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %tyg% neq 1429 (set /a gcf=%gcf%-244) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %i% leq 2010 (set /a i=%i%+120) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %rf% equ -455 (set /a cty=%cty%+40) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %wow% leq 2900 (set /a x=%x%+433) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %cty% neq 162 (set /a u=%u%+553) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %u% leq -4177 (set /a jq=%jq%-329) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %g% gtr 387 (set /a aqr=%aqr%+319) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %wow% gtr 2904 (set /a esb=%esb%-259) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %vyy% lss 2415 (set /a jq=%jq%+590) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %d% equ -467 (set /a tyg=%tyg%+211) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %l% neq -3561 (set /a rjx=%rjx%+209) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %aqr% geq 281 (set /a tyg=%tyg%-564) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %u% neq -4186 (set /a aqr=%aqr%+860) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %g% geq 387 (set /a wn=%wn%-298) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %i% lss 2122 (set /a x=%x%-951) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %cty% geq 163 (set /a j=%j%-141) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %wow% neq 2910 (set /a l=%l%+780) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %esb% gtr -3491 (set /a zp=%zp%-796) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %qc% lss -3628 (set /a j=%j%-652) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %i% leq 2128 (set /a cn=%cn%-101) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %gcf% lss -573 (set /a cty=%cty%-169) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %epp% leq -309 (set /a dma=%dma%+544) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %zp% leq 4598 (set /a vyy=%vyy%+261) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %esb% equ -3487 (set /a rf=%rf%+166) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %rf% equ -455 (set /a aqr=%aqr%-865) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %rjx% leq 148 (set /a u=%u%+14) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %dma% lss 538 (set /a vyy=%vyy%-518) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %cn% leq 1988 (set /a aqr=%aqr%+30) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %wow% leq 2912 (set /a rf=%rf%-818) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %l% gtr -2786 (set /a js=%js%+116) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %gy% gtr 939 (set /a jq=%jq%+707) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %x% lss -1176 (set /a jq=%jq%+673) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %rjx% geq 141 (set /a wow=%wow%-94) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %esb% gtr -3488 (set /a esb=%esb%-654) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %i% neq 2127 (set /a jq=%jq%+982) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %i% gtr 2122 (set /a cn=%cn%+479) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %rjx% geq 144 (set /a js=%js%-530) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %gcf% neq -578 (set /a wn=%wn%+37) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %cn% gtr 2458 (set /a esb=%esb%+917) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %wn% gtr 923 (set /a l=%l%-519) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %wn% equ 933 (set /a uxa=%uxa%-671) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %cn% geq 2457 (set /a zp=%zp%-269) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %wn% equ 933 (set /a esb=%esb%-329) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %d% leq -468 (set /a tyg=%tyg%-490) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %wn% gtr 930 (set /a dma=%dma%-817) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %u% neq -4164 (set /a cty=%cty%-650) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %l% geq -3309 (set /a rf=%rf%+804) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %esb% equ -3549 (set /a dma=%dma%-629) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %epp% lss -317 (set /a l=%l%+588) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %zp% geq 4318 (set /a zp=%zp%-738) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %wn% neq 924 (set /a l=%l%+772) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %js% leq -317 (set /a epp=%epp%+423) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %qc% neq -3637 (set /a g=%g%-781) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %tyg% gtr 1062 (set /a uxa=%uxa%-540) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %j% neq 1127 (set /a gcf=%gcf%-120) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %wow% geq 2819 (set /a d=%d%+294) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %u% geq -4169 (set /a i=%i%+108) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %zp% gtr 3581 (set /a x=%x%+117) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %gy% gtr 950 (set /a i=%i%-434) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %zp% geq 3587 (set /a jq=%jq%+749) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %tyg% neq 1063 (set /a gcf=%gcf%+342) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %wn% neq 932 (set /a j=%j%-910) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %rjx% gtr 142 (set /a u=%u%-353) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %esb% equ -3549 (set /a qc=%qc%-478) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %wn% neq 933 (set /a uxa=%uxa%-992) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %gcf% equ -356 (set /a cty=%cty%+628) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %dma% neq -916 (set /a u=%u%+527) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %j% geq 211 (set /a aqr=%aqr%-354) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %x% geq -1062 (set /a d=%d%-633) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %js% neq -326 (set /a l=%l%-920) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %j% gtr 203 (set /a wn=%wn%+122) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %gcf% equ -356 (set /a x=%x%-907) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %epp% neq 105 (set /a epp=%epp%+112) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %u% geq -3988 (set /a wn=%wn%-322) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %wn% neq 1055 (set /a j=%j%+934) 
if %j% gtr !max! (set maxn=j & set max=%j%) 
if %uxa% geq 448 (set /a g=%g%-366) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %wn% leq 1063 (set /a uxa=%uxa%+720) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %gy% leq 947 (set /a zp=%zp%+8) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %epp% leq 110 (set /a esb=%esb%+199) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %j% neq 220 (set /a cn=%cn%+122) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %g% leq -763 (set /a l=%l%+810) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %yzp% lss 3521 (set /a cty=%cty%-435) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %i% geq 2230 (set /a zp=%zp%-615) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %uxa% neq 1170 (set /a jq=%jq%+445) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %u% gtr -3994 (set /a gy=%gy%-654) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %dma% equ -914 (set /a tyg=%tyg%-48) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %dma% lss -905 (set /a gcf=%gcf%-346) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %zp% geq 2980 (set /a wn=%wn%-660) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %esb% geq -3359 (set /a x=%x%-242) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %rjx% lss 154 (set /a gy=%gy%+28) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %esb% leq -3341 (set /a tyg=%tyg%-602) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %l% gtr -2061 (set /a jq=%jq%-380) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %js% leq -308 (set /a i=%i%+502) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %qc% lss -4109 (set /a uxa=%uxa%-255) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %l% equ -2051 (set /a u=%u%+617) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %esb% leq -3347 (set /a rjx=%rjx%-864) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %vyy% equ 2157 (set /a u=%u%+465) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %i% lss 2740 (set /a tyg=%tyg%-629) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %u% lss -2907 (set /a d=%d%-28) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %cn% leq 2585 (set /a epp=%epp%-430) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %yzp% equ 3515 (set /a vyy=%vyy%+740) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %gy% gtr 315 (set /a js=%js%+387) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %gy% geq 310 (set /a vyy=%vyy%-792) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %wn% gtr 389 (set /a l=%l%-89) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %wow% gtr 2810 (set /a qc=%qc%+149) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %cn% equ 2583 (set /a gy=%gy%+510) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %g% neq -757 (set /a d=%d%+381) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %gcf% neq -694 (set /a x=%x%+633) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %j% gtr 222 (set /a wn=%wn%+677) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %i% geq 2729 (set /a wn=%wn%-605) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %rf% lss -474 (set /a zp=%zp%-794) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %js% geq 61 (set /a dma=%dma%-560) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %wow% leq 2819 (set /a rjx=%rjx%+364) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %g% neq -774 (set /a jq=%jq%+429) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %j% leq 215 (set /a rjx=%rjx%+305) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %tyg% leq -219 (set /a epp=%epp%-254) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %qc% lss -3955 (set /a i=%i%+106) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %zp% lss 2983 (set /a g=%g%-514) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %u% geq -2911 (set /a dma=%dma%+617) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %aqr% gtr -40 (set /a gy=%gy%+81) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %wn% lss -201 (set /a g=%g%-722) 
if %g% gtr !max! (set maxn=g & set max=%g%) 
if %tyg% geq -210 (set /a zp=%zp%+46) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %gy% leq 830 (set /a yzp=%yzp%-720) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %epp% geq -318 (set /a cty=%cty%+675) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %cn% geq 2574 (set /a qc=%qc%-727) 
if %qc% gtr !max! (set maxn=qc & set max=%qc%) 
if %wow% neq 2811 (set /a zp=%zp%+458) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %yzp% leq 2800 (set /a jq=%jq%-547) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %l% equ -2140 (set /a uxa=%uxa%-443) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %tyg% equ -212 (set /a x=%x%-76) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %aqr% neq -36 (set /a x=%x%+11) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %aqr% leq -37 (set /a x=%x%-1000) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %gy% neq 822 (set /a l=%l%+384) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %aqr% equ -40 (set /a u=%u%+329) 
if %u% gtr !max! (set maxn=u & set max=%u%) 
if %wn% gtr -202 (set /a x=%x%+432) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %tyg% lss -202 (set /a uxa=%uxa%+530) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %js% lss 71 (set /a i=%i%+798) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %i% equ 3645 (set /a dma=%dma%-503) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %uxa% leq 1264 (set /a dma=%dma%+69) 
if %dma% gtr !max! (set maxn=dma & set max=%dma%) 
if %js% neq 70 (set /a d=%d%-571) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %u% geq -2588 (set /a wn=%wn%+134) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %rjx% gtr -48 (set /a i=%i%+813) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %cn% lss 2585 (set /a epp=%epp%-735) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %dma% geq -790 (set /a aqr=%aqr%+223) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %dma% geq -789 (set /a uxa=%uxa%+86) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %aqr% lss 188 (set /a cty=%cty%+127) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %uxa% equ 1349 (set /a cty=%cty%+472) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %cty% geq 791 (set /a cn=%cn%+780) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %rjx% equ -49 (set /a cn=%cn%+528) 
if %cn% gtr !max! (set maxn=cn & set max=%cn%) 
if %d% neq -754 (set /a l=%l%+669) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %epp% neq -1052 (set /a gcf=%gcf%-427) 
if %gcf% gtr !max! (set maxn=gcf & set max=%gcf%) 
if %dma% geq -797 (set /a rf=%rf%+465) 
if %rf% gtr !max! (set maxn=rf & set max=%rf%) 
if %g% neq -2005 (set /a epp=%epp%+452) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %i% neq 3648 (set /a epp=%epp%+922) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %js% neq 72 (set /a wow=%wow%-516) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %epp% equ 314 (set /a esb=%esb%+623) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %cn% equ 3111 (set /a wn=%wn%+434) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %yzp% equ 2794 (set /a rjx=%rjx%+698) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %epp% lss 319 (set /a vyy=%vyy%+150) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %yzp% neq 2797 (set /a rjx=%rjx%+343) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %gy% leq 831 (set /a jq=%jq%-390) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %l% geq -1093 (set /a yzp=%yzp%-296) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %esb% gtr -2730 (set /a yzp=%yzp%-676) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %epp% lss 318 (set /a js=%js%-320) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %g% lss -1996 (set /a jq=%jq%+44) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %zp% geq 3444 (set /a esb=%esb%+425) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %esb% equ -2727 (set /a i=%i%-817) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %esb% neq -2727 (set /a cty=%cty%-336) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %uxa% lss 1341 (set /a epp=%epp%-90) 
if %epp% gtr !max! (set maxn=epp & set max=%epp%) 
if %epp% neq 312 (set /a zp=%zp%-554) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %epp% neq 319 (set /a js=%js%+299) 
if %js% gtr !max! (set maxn=js & set max=%js%) 
if %wn% leq 366 (set /a zp=%zp%-92) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %rf% gtr -12 (set /a wow=%wow%+443) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %i% lss 2825 (set /a gy=%gy%+962) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %d% gtr -748 (set /a vyy=%vyy%+381) 
if %vyy% gtr !max! (set maxn=vyy & set max=%vyy%) 
if %js% leq 54 (set /a wn=%wn%+212) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %gcf% neq -1127 (set /a esb=%esb%+944) 
if %esb% gtr !max! (set maxn=esb & set max=%esb%) 
if %j% neq 211 (set /a cty=%cty%-985) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %uxa% geq 1340 (set /a aqr=%aqr%-697) 
if %aqr% gtr !max! (set maxn=aqr & set max=%aqr%) 
if %gcf% lss -1120 (set /a wow=%wow%-459) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %dma% geq -796 (set /a i=%i%+728) 
if %i% gtr !max! (set maxn=i & set max=%i%) 
if %tyg% geq -216 (set /a cty=%cty%-277) 
if %cty% gtr !max! (set maxn=cty & set max=%cty%) 
if %aqr% equ -505 (set /a rjx=%rjx%+279) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %zp% geq 2793 (set /a yzp=%yzp%-38) 
if %yzp% gtr !max! (set maxn=yzp & set max=%yzp%) 
if %epp% equ 314 (set /a zp=%zp%-221) 
if %zp% gtr !max! (set maxn=zp & set max=%zp%) 
if %x% leq -2630 (set /a d=%d%+628) 
if %d% gtr !max! (set maxn=d & set max=%d%) 
if %esb% equ -1783 (set /a uxa=%uxa%+846) 
if %uxa% gtr !max! (set maxn=uxa & set max=%uxa%) 
if %x% leq -2625 (set /a rjx=%rjx%-154) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %wow% geq 2290 (set /a l=%l%+541) 
if %l% gtr !max! (set maxn=l & set max=%l%) 
if %vyy% lss 2636 (set /a wow=%wow%-777) 
if %wow% gtr !max! (set maxn=wow & set max=%wow%) 
if %uxa% geq 2195 (set /a rjx=%rjx%+492) 
if %rjx% gtr !max! (set maxn=rjx & set max=%rjx%) 
if %yzp% lss 1791 (set /a gy=%gy%+881) 
if %gy% gtr !max! (set maxn=gy & set max=%gy%) 
if %l% geq -1095 (set /a x=%x%-24) 
if %x% gtr !max! (set maxn=x & set max=%x%) 
if %x% geq -2658 (set /a jq=%jq%-82) 
if %jq% gtr !max! (set maxn=jq & set max=%jq%) 
if %aqr% gtr -519 (set /a tyg=%tyg%-763) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %esb% lss -1773 (set /a wn=%wn%+242) 
if %wn% gtr !max! (set maxn=wn & set max=%wn%) 
if %d% equ -119 (set /a tyg=%tyg%+574) 
if %tyg% gtr !max! (set maxn=tyg & set max=%tyg%) 
if %i% gtr 3540 (set /a d=%d%-423) 
if %d% gtr !max! (set maxn=d & set max=%d%) 

echo !maxn! !max!
pause